apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-producer-api
  name: location-producer-api
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30005
  selector:
    service: location-producer-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-producer-api
  name: location-producer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-producer-api
  template:
    metadata:
      labels:
        service: location-producer-api
    spec:
      containers:
      - image: 124545/api-location-producer:latest
        name: location-producer-api
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: kafka-location-map
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-location-map
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always
