apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-consumer-api
  name: location-consumer-api
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30004
  selector:
    service: location-consumer-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-consumer-api
  name: location-consumer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-consumer-api
  template:
    metadata:
      labels:
        service: location-consumer-api
    spec:
      containers:
      - image: 124545/api-location-consumer:latest
        name: location-consumer-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: kafka-location-map
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-location-map
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always
