# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import person_kafka_event_pb2 as person__kafka__event__pb2


class PersonEventItemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/PersonEventItemService/Create',
                request_serializer=person__kafka__event__pb2.PersonEventMessage.SerializeToString,
                response_deserializer=person__kafka__event__pb2.PersonEventMessage.FromString,
                )
        self.Get = channel.unary_unary(
                '/PersonEventItemService/Get',
                request_serializer=person__kafka__event__pb2.Empty.SerializeToString,
                response_deserializer=person__kafka__event__pb2.PersonEventMessage.FromString,
                )


class PersonEventItemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonEventItemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=person__kafka__event__pb2.PersonEventMessage.FromString,
                    response_serializer=person__kafka__event__pb2.PersonEventMessage.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=person__kafka__event__pb2.Empty.FromString,
                    response_serializer=person__kafka__event__pb2.PersonEventMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PersonEventItemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PersonEventItemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PersonEventItemService/Create',
            person__kafka__event__pb2.PersonEventMessage.SerializeToString,
            person__kafka__event__pb2.PersonEventMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PersonEventItemService/Get',
            person__kafka__event__pb2.Empty.SerializeToString,
            person__kafka__event__pb2.PersonEventMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
